---
# tasks file for apache
# 1 - installation of apache with apt module
- name: "apache installation"
  apt:
    name: "apache2"
    state: "present"

# 2 - activate apache service
- name: "apache service activation"
  service:
    name: "apache2"
    state: "started"
    enabled: "yes"

# 3 - this task calls to another configuration file in order to install PHP .
# It can be executed only if the PHP_install variable is true (default is false)
- name: "install php package"
  include: "php-install.yml"
  when: php_install|default(False)|bool
